name: Bug Report
description: File a bug report to help us improve Brain-Forge
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - hkevin01

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Before submitting, please check if this issue has already been reported.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Data Acquisition
        - Signal Processing
        - Brain Mapping
        - Neural Simulation
        - Visualization
        - API
        - Hardware Interface
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Feature unusable)
        - Medium (Feature partially working)
        - Low (Minor issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Python Version: [e.g. 3.11.0]
        - Brain-Forge Version: [e.g. 0.1.0]
        - Hardware: [e.g. OMP Helmet, Kernel Optical]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
